In [1]:
#Importing the required libraries
import pandas as pd
import numpy as np

#Let us load the dataset from the data folder
# The ".." means to go up one folder level
# Then '/data/' goes into the data folder

df = pd.read_csv('../data/Mall_Customers.csv')

#Let us display the first 5 rows of the dataset
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [3]:
#Let us explore the dataset to understand its structure and contents
#Checking how many rows and columns we have
print("Dataset shape:", df.shape)
print("Rows:", df.shape[0], "| Columns:", df.shape[1])

Dataset shape: (200, 5)
Rows: 200 | Columns: 5

In [4]:
#Show all column names
print("Column names:", df.columns.tolist())

Column names: ['CustomerID', 'Gender', 'Age', 'Annual Income (k$)', 'Spending Score (1-100)']

In [5]:
# Check the datatypes for each column
print("Print datatypes:")
print(df.dtypes)

Print datatypes:
CustomerID                int64
Gender                      str
Age                       int64
Annual Income (k$)        int64
Spending Score (1-100)    int64
dtype: object

In [6]:
# Let us check for any missing values in the dataset
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [7]:
# Let us check for duplicates in the dataset
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

In [8]:
# Let us get statistical summary of the dataset
print("Statistical summary of the dataset:")
print(df.describe())

Statistical summary of the dataset:
       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [9]:
# Checking for unique values in the gender column
print("Unique genders:", df['Gender'].unique())
print("Count of each gender:")
print(df['Gender'].value_counts())

Unique genders: <ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str
Count of each gender:
Gender
Female    112
Male       88
Name: count, dtype: int64

In [10]:
# View dataset differently
df.tail()

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [12]:
#Get a random sample of the rows
df.sample(10)

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
179         180    Male   35                  93                      90
12           13  Female   58                  20                      15
10           11    Male   67                  19                      14
60           61    Male   70                  46                      56
8             9    Male   64                  19                       3
83           84  Female   46                  54                      44
170         171    Male   40                  87                      13
44           45  Female   49                  39                      28
137         138    Male   32                  73                      73
89           90  Female   50                  58                      46

In [13]:
# Let us view specific columns in the dataset
df[['Age', 'Spending Score (1-100)']].head()

   Age  Spending Score (1-100)
0   19                      39
1   21                      81
2   20                       6
3   23                      77
4   31                      40